### ISSUE TITLE
Reading local IP from config property breaks CF login when resurrected

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/cf-registrar#4]
The cf-registrar gets the local IP used to register at the router from its config. The IP is determined when the [configuration template](https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/templates/cf-registrar.config.yml.erb#L14) is rendered by erb. 

This is a problem when the UAA gets resurrected by the BOSH Healthmonitor. Rendered configuration templates are cached in the BOSH director's blobstore. These template are used when resurrecting the VM, although it might get a different IP address. The UAA will then register with a wrong IP at the router and you cannot log into CF anymore.

All other CF components should not be affected as they don't use the cf-registrar.

As a solution, the cf-registrar could make sure to get the actual IP when started and not from a config property.

**Comment by voelzmo** [comment]
@cppforlife This might also be of interest for you? The director's caching mechanism for rendered templates has some funny side effects when properties are used that don't come the deployment manifest.

**Comment by jpalermo** [comment]
Closed due to bug created in BOSH backlog: #5
