### ISSUE TITLE
cf registrar not sending route messages to NATS

### ISSUE THREAD

**Issue by jianghaitao** [cloudfoundry/cf-registrar#7]
I deployed a CF cluster, every component seems working as reported by BOSH and monit. However, I noticed that routes for UAA and HM9000 are missing from gorouter. 

Looking at the UAA, cf registrar are not sending route messages:
```
Oct  6 23:28:12 ip-10-164-196-28 vcap.uaa_cf-registrar[5604]: {"timestamp":1444174092.2810595,"message":"Reading varz config from /var/vcap/jobs/uaa/config/varz.yml","log_level":"info","source":"cf-registrar","data":{},"thread_id":70080760730400,"fiber_id":70080766900960,"process_id":5604,"file":"/var/vcap/data/packages/uaa/c712cd0a90488194d2180aea184ce179dd6fb7ab.1-0d98f1629870590559bda55b78e4ff0569bea81b/vcap-common/vendor/bundle/ruby/2.1.0/gems/cf-registrar-1.0.3/bin/cf-registrar","lineno":25,"method":"<top (required)>"}
Oct  6 23:28:12 ip-10-164-196-28 vcap.uaa_cf-registrar[5604]: {"timestamp":1444174092.2813783,"message":"Config {\"logging\"=>{\"file\"=>\"/var/vcap/sys/log/uaa/cf-registrar.log\", \"syslog\"=>\"vcap.uaa_cf-registrar\", \"level\"=>\"debug\"}, \"message_bus_servers\"=>[\"nats://nats:c1oudc0w@0.nats.default.openstack03.microbosh:4222\"], \"uri\"=>[\"uaa.192.168.12.157.xip.io\", \"*.uaa.192.168.12.157.xip.io\", \"login.192.168.12.157.xip.io\", \"*.login.192.168.12.157.xip.io\"], \"host\"=>\"10.11.1.65\", \"index\"=>0, \"port\"=>8080, \"tags\"=>{\"component\"=>\"uaa\"}, \"varz\"=>{\"username\"=>\"4701-10880-25430-11282\", \"password\"=>\"29200-8008-25111-4940\", \"type\"=>\"uaa\"}}","log_level":"debug","source":"cf-registrar","data":{},"thread_id":70080760730400,"fiber_id":70080766900960,"process_id":5604,"file":"/var/vcap/data/packages/uaa/c712cd0a90488194d2180aea184ce179dd6fb7ab.1-0d98f1629870590559bda55b78e4ff0569bea81b/vcap-common/vendor/bundle/ruby/2.1.0/gems/cf-registrar-1.0.3/bin/cf-registrar","lineno":30,"method":"<top (required)>"}
Oct  6 23:28:12 ip-10-164-196-28 vcap.uaa_cf-registrar[5604]: {"timestamp":1444174092.2819228,"message":"Connected to NATS - varz registration","log_level":"info","source":"cf.registrar","data":{},"thread_id":70080760730400,"fiber_id":70080766900960,"process_id":5604,"file":"/var/vcap/data/packages/uaa/c712cd0a90488194d2180aea184ce179dd6fb7ab.1-0d98f1629870590559bda55b78e4ff0569bea81b/vcap-common/vendor/bundle/ruby/2.1.0/gems/cf-registrar-1.0.3/lib/cf/registrar.rb","lineno":51,"method":"register_varz_credentials"}
Oct  6 23:28:12 ip-10-164-196-28 vcap.uaa_cf-registrar[5604]: {"timestamp":1444174092.2847972,"message":"Announcing start up vcap.component.announce","log_level":"info","source":"cf.registrar","data":{},"thread_id":70080760730400,"fiber_id":70080766900960,"process_id":5604,"file":"/var/vcap/data/packages/uaa/c712cd0a90488194d2180aea184ce179dd6fb7ab.1-0d98f1629870590559bda55b78e4ff0569bea81b/vcap-common/vendor/bundle/ruby/2.1.0/gems/cf-registrar-1.0.3/lib/cf/registrar.rb","lineno":58,"method":"register_varz_credentials"}
```
and then stuck.

Any help/hint would be highly appreciated.

**Comment by jpalermo** [comment]
Hi @jianghaitao 

The uaa job no longer uses the cf-registrar for registering routes.

The new method involves co-locating the `route_registrar` template on the same vm. And then specifying properties that tell it to register the routes for login and uaa.

The configuration is somewhat spread out in the default templates (to allow parts to be overridden), but here are the relevant sections. Let me know if you have any other questions.

https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L144
https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L162
https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L324

Joseph
CF Release Integration Team

**Comment by jianghaitao** [comment]
Thanks for the info.  I think we use release 218.

I am trying to fix a BOSH deployed CF's UAA in place, it has following related yml files:
```
/var/vcap/data/jobs/uaa/*/config/cf-registrar/config.yml
/var/vcap/data/jobs/uaa/*/config/newrelic.yml
/var/vcap/data/jobs/uaa/*/config/login.yml
/var/vcap/data/jobs/uaa/*/config/uaa.yml
/var/vcap/data/jobs/uaa/*/config/varz.yml
```
Among them I think config/cf-registrar/config.yml is what we care about
```
logging:
  file: /var/vcap/sys/log/uaa/cf-registrar.log
  syslog: vcap.uaa_cf-registrar
  level: debug

message_bus_servers:

  - nats://nats:c1oudc0w@0.nats.default.openstack03.microbosh:4222

uri:
  - uaa.192.168.12.157.xip.io
  - '*.uaa.192.168.12.157.xip.io'
  - login.192.168.12.157.xip.io
  - '*.login.192.168.12.157.xip.io'
host: 10.11.1.65
index: 0
port: 8080
tags:
  component: uaa
varz:
  file: /var/vcap/jobs/uaa/config/varz.yml
```
Does it look right to you? As you can see uris are defined. 

If uaa_cf-registrar is no longer periodically send route registration messages, which process will? UAA only has uaa and uaa_cf-registrar processes. As far as I understand, each CF components needs to send route.register messages periodically. Same questions to HM9000 as well.

Thanks

**Comment by jpalermo** [comment]
Yes, as of 218, the cf-registrar is no longer responsible for registering the route for UAA. It is still used for registering the varz endpoint, which is why you still see it running.

You can see this mentioned in the release notes:
https://github.com/cloudfoundry/cf-release/releases/tag/v218

You'll need to add the route_registrar template to the UAA job in the manifest, as well as the properties which say which routes to register for that job. You can see the details in my previous response.
